version: '3.3'
services:
  btc:
    build:
      context: ./btc/
      dockerfile: Dockerfile
    image: crypto-btc
    container_name: crypto-btc
    restart: always
    command:
      -printtoconsole
    ports:
      - 10001:10001
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
      - ./btc/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf

  ltc:
    build:
      context: ./ltc/
      dockerfile: Dockerfile
    image: crypto-ltc
    container_name: crypto-ltc
    restart: always
    command:
      -printtoconsole
    ports:
      - 10002:10002
    volumes:
      - litecoin_data:/home/litecoin/.litecoin
      - ./ltc/litecoin.conf:/home/litecoin/.litecoin/litecoin.conf

  dash:
    build:
      context: ./dash/
      dockerfile: Dockerfile
    image: crypto-dash
    container_name: crypto-dash
    restart: always
    command:
      -printtoconsole
    ports:
      - 10003:10003
    volumes:
      - dash_data:/home/dash/.dashcore
      - ./dash/dash.conf:/home/dash/.dashcore/dash.conf


  btg:
    build:
      context: ./btg/
      dockerfile: Dockerfile
    image: crypto-btg
    container_name: crypto-btg
    restart: always
    command:
      -printtoconsole
    ports:
      - 10006:10006
    volumes:
      - bitcoingold_data:/home/bitcoingold/.bitcoingold
      - ./btg/bitcoin.conf:/home/bitcoingold/.bitcoingold/bitcoingold.conf


  bch:
    build:
      context: ./bch/
      dockerfile: Dockerfile
    image: crypto-bch
    container_name: crypto-bch
    restart: always
    command:
      -printtoconsole
    ports:
      - 10005:10005
    volumes:
      - bitcoincash_data:/home/bitcoin/.bitcoin
      - ./bch/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf


  zec:
    build:
      context: ./zec/
      dockerfile: Dockerfile
    image: crypto-zec
    container_name: crypto-zec
    restart: always
#    command:
#      -printtoconsole
    ports:
      - 10004:10004
    volumes:
      - zcash_data:/root/.zcash
      - ./zec/zcash.conf:/root/.zcash/zcash.conf

  eth:
    build: 
      context: ./eth/
      dockerfile: Dockerfile
    image: crypto-eth
    container_name: crypto-eth
#    command: --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --rpc --rpcaddr="0.0.0.0"
    restart: always
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - eth_data:/root/.ethereum
      - /etc/localtime:/etc/localtime:ro

  eth-netstats:
    build:
      context: ./eth/
      dockerfile: Dockerfile.netstats
    restart: on-failure
    container_name: crypto-eth-netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: ${NETWORK}

volumes:
  bitcoin_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/bitcoin"

  litecoin_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/litecoin"

  dash_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/dash"

  bitcoingold_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/bitcoingold"

  bitcoincash_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/bitcoincash"

  zcash_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/zcash"

  eth_data:
    driver: local-persist
    driver_opts:
      mountpoint: "${LOCAL_VOLUME_MOUNT_POINT}/ethereum"
